#!/usr/bin/env python3
import os
import sys


def escape_string(value: str) -> str:
    return (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", '\\n" \\\n    "')
    )


def file_to_c_string(filepath: str, var_name: str) -> str:
    with open(filepath, "r", encoding="utf-8") as file:
        content = file.read()
    escaped = escape_string(content)
    return f'const char* {var_name} = "{escaped}";\n\n'


def main() -> int:
    if len(sys.argv) < 4:
        print("Usage: generate_embed.py <output.h> <file1> <var1> [<file2> <var2> ...]")
        return 1

    output_file = sys.argv[1]
    pairs = []
    idx = 2
    while idx < len(sys.argv):
        if idx + 1 >= len(sys.argv):
            print(f"Error: Missing variable name for file {sys.argv[idx]}")
            return 1
        pairs.append((sys.argv[idx], sys.argv[idx + 1]))
        idx += 2

    lines = []
    lines.append("// Auto-generated file - DO NOT EDIT\n")
    lines.append("// Generated by cmake/user/generate_embed.py\n\n")
    lines.append("#ifndef EMBED_H\n")
    lines.append("#define EMBED_H\n\n")

    for filepath, var_name in pairs:
        if not os.path.exists(filepath):
            print(f"Warning: {filepath} not found, embedding empty string for {var_name}")
            lines.append(f'const char* {var_name} = "";\n\n')
            continue
        lines.append(file_to_c_string(filepath, var_name))

    lines.append("#endif // EMBED_H\n")

    with open(output_file, "w", encoding="utf-8") as file:
        file.write("".join(lines))

    print(f"Generated {output_file}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
