#!/usr/bin/env python3
import sys
import os
from pathlib import Path

def replace_all_occurrences_in_file(filename, old_string, new_string):
    # Safely read the file content
    with open(filename, 'r') as f:
        file_content = f.read()

    # Perform the replacement (all occurrences are replaced by default)
    modified_content = file_content.replace(old_string, new_string)

    # Safely write the modified content back to the file
    with open(filename, 'w') as f:
        f.write(modified_content)

def escape_string(s):
    return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n" \\\n    "')

def file_to_string(filepath, var_name):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    escaped = escape_string(content)
    return f'const char* {var_name} = "{escaped}";\n\n'

def main():
    if len(sys.argv) < 4:
        print('Usage: generate_embed.py <output.h> <file1> <var1> [<file2> <var2> ...]')
        sys.exit(1)
    
    output_file = sys.argv[1]
    files_and_vars = []
    
    i = 2
    while i < len(sys.argv):
        if i + 1 >= len(sys.argv):
            print(f'Error: Missing variable name for file {sys.argv[i]}')
            sys.exit(1)
        files_and_vars.append((sys.argv[i], sys.argv[i + 1]))
        i += 2
    
    # Generate header
    output = []
    output.append('// Auto-generated file - DO NOT EDIT\n')
    output.append('// Generated by CMake from embedded resources\n\n')
    output.append('#ifndef EMBED_H\n')
    output.append('#define EMBED_H\n\n')
    
    for filepath, var_name in files_and_vars:
        if not os.path.exists(filepath):
            print(f'Warning: File {filepath} does not exist, using empty string')
            output.append(f'const char* {var_name} = "";\n\n')
        else:
            #if var_name == "MAIN_HTML":
            #    replace_all_occurrences_in_file(filepath, '"/assets', '"com.machotkey.machotkey://resources/main/assets')
            output.append(file_to_string(filepath, var_name))
    
    output.append('#endif // EMBED_H\n')
    
    # Write to file
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(''.join(output))
    
    print(f'Generated {output_file}')

    #for entry in Path('/Users/Shared/VSCode/machotkey/build/machotkey.app/Contents/Resources/main/assets').iterdir():
    #    if entry.is_file():
    #        replace_all_occurrences_in_file(entry.resolve(), '"/assets', '"com.machotkey.machotkey://resources/main/assets')

if __name__ == '__main__':
    main()
